/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inatel.Interface;

import com.inatel.Integracao.DAO.AtendimentoDAO;
import com.inatel.Integracao.DAO.FuncionarioDAO;
import com.inatel.Integracao.DAO.PacienteDAO;
import com.inatel.Integracao.Model.Atendimento;
import com.inatel.Integracao.Model.Funcionario;
import com.inatel.Integracao.Model.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author ppg10
 */
public class TelaMarcarHorarios extends javax.swing.JFrame {

    /**
     * Creates new form TelaMarcarHorarios
     */
    public TelaMarcarHorarios() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        dentistaAtendimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        procedimentoAtendimento = new javax.swing.JFormattedTextField();
        prontoAtendimento = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        voltarCadastro = new javax.swing.JButton();
        nomePacienteAtendimento = new javax.swing.JTextField();
        horarioAtendimento = new javax.swing.JTextField();
        dataAtendimento = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel5.setText("Paciente");
        jLabel5.setAlignmentY(0.0F);

        dentistaAtendimento.setToolTipText("Nome");
        dentistaAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dentistaAtendimentoActionPerformed(evt);
            }
        });

        jLabel7.setText("Dentista");
        jLabel7.setAlignmentY(0.0F);

        jLabel6.setText("Procedimento");
        jLabel6.setAlignmentY(0.0F);

        procedimentoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedimentoAtendimentoActionPerformed(evt);
            }
        });

        prontoAtendimento.setBackground(new java.awt.Color(62, 190, 76));
        prontoAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        prontoAtendimento.setText("Pronto");
        prontoAtendimento.setToolTipText("Pronto");
        prontoAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prontoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prontoAtendimentoActionPerformed(evt);
            }
        });

        jLabel9.setText("Data");
        jLabel9.setAlignmentY(0.0F);

        jLabel1.setBackground(new java.awt.Color(62, 190, 76));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 190, 76));
        jLabel1.setText("Novo");
        jLabel1.setToolTipText("");

        jLabel10.setText("Horário");
        jLabel10.setAlignmentY(0.0F);

        jLabel2.setBackground(new java.awt.Color(62, 190, 76));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 190, 76));
        jLabel2.setText("Atendimento");
        jLabel2.setToolTipText("");

        voltarCadastro.setBackground(new java.awt.Color(62, 190, 76));
        voltarCadastro.setForeground(new java.awt.Color(255, 255, 255));
        voltarCadastro.setText("Voltar");
        voltarCadastro.setToolTipText("Pronto");
        voltarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadastroActionPerformed(evt);
            }
        });

        nomePacienteAtendimento.setToolTipText("Nome");
        nomePacienteAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePacienteAtendimentoActionPerformed(evt);
            }
        });

        horarioAtendimento.setToolTipText("Nome");
        horarioAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioAtendimentoActionPerformed(evt);
            }
        });

        dataAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAtendimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(procedimentoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(prontoAtendimento))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(nomePacienteAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dentistaAtendimento)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(dataAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(horarioAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(voltarCadastro)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(voltarCadastro)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomePacienteAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dentistaAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horarioAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(procedimentoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(prontoAtendimento)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dentistaAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dentistaAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dentistaAtendimentoActionPerformed

    private void procedimentoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedimentoAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procedimentoAtendimentoActionPerformed

    private void prontoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prontoAtendimentoActionPerformed
        // TODO add your handling code here:
        inserirNovoAtendimento();
    }//GEN-LAST:event_prontoAtendimentoActionPerformed

    private void voltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadastroActionPerformed
        // TODO add your handling code here:
        voltarTelaInicial();
    }//GEN-LAST:event_voltarCadastroActionPerformed

    private void nomePacienteAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePacienteAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePacienteAtendimentoActionPerformed

    private void horarioAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioAtendimentoActionPerformed

    private void dataAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAtendimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMarcarHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMarcarHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMarcarHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMarcarHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMarcarHorarios().setVisible(true);
            }
        });
    }

    public void voltarTelaInicial(){
        TelaInicial t = new TelaInicial();
        this.setVisible(false);
        t.setVisible(true);
    }
    
    public void inserirNovoAtendimento(){
        PacienteDAO p = new PacienteDAO();
        FuncionarioDAO f = new FuncionarioDAO();
        AtendimentoDAO a = new AtendimentoDAO();
        int idPaciente;
        int idFuncionario;
        Atendimento atendimento;
        if("".equals(nomePacienteAtendimento.getText()) || "".equals(dentistaAtendimento.getText())
                || "".equals(dataAtendimento.getText()) || "".equals(horarioAtendimento.getText()) 
                || "".equals(procedimentoAtendimento.getText())){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente");
        }
        else if(p.buscarPaciente(nomePacienteAtendimento.getText())== true && f.buscarFuncionario(dentistaAtendimento.getText()) == true){
            idPaciente = p.buscarIdPaciente(nomePacienteAtendimento.getText());
            idFuncionario = f.buscarIdFuncionario(dentistaAtendimento.getText());
            atendimento = new Atendimento(dataAtendimento.getText(),
                    horarioAtendimento.getText(),procedimentoAtendimento.getText(),idFuncionario,idPaciente);
            boolean inserirAtendimento = a.inserirAtendimento(atendimento);
            if (inserirAtendimento == true){
                JOptionPane.showMessageDialog(null,"Novo atendimento adicionado.");
            } 
        }
        else if(p.buscarPaciente(nomePacienteAtendimento.getText())== false){
            JOptionPane.showMessageDialog(null,"Nome do paciente inexistente.");
        }
        else if(f.buscarFuncionario(dentistaAtendimento.getText()) == false){
            JOptionPane.showMessageDialog(null,"Nome do dentista inexistente.");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dataAtendimento;
    private javax.swing.JTextField dentistaAtendimento;
    private javax.swing.JTextField horarioAtendimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomePacienteAtendimento;
    private javax.swing.JFormattedTextField procedimentoAtendimento;
    private javax.swing.JButton prontoAtendimento;
    private javax.swing.JButton voltarCadastro;
    // End of variables declaration//GEN-END:variables
}
