/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inatel.Interface;

import com.inatel.Integracao.DAO.EmpresaDAO;
import javax.swing.JOptionPane;
import com.inatel.Integracao.DAO.FuncionarioDAO;
import com.inatel.Integracao.Model.Funcionario;

/**
 *
 * @author ppg10
 */
public class TelaAdicionar extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionar
     */
    public TelaAdicionar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        estadoPaciente = new javax.swing.JComboBox<>();
        prontoPaciente = new javax.swing.JButton();
        especialidadeFuncionario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        funcaoDentista = new javax.swing.JCheckBox();
        funcaoAuxiliar = new javax.swing.JCheckBox();
        nomeFuncionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        prontoFuncionario = new javax.swing.JButton();
        craFuncionario = new javax.swing.JFormattedTextField();
        nomePaciente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cidadePaciente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        telefonePaciente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        horarioInicio = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        horarioFim = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cpfPaciente = new javax.swing.JFormattedTextField();
        voltarCadastro = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        empresaFuncionario = new javax.swing.JTextField();
        senhaFuncionario = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        emailPaciente3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        emailPaciente4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        estadoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF" }));
        estadoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoPacienteActionPerformed(evt);
            }
        });

        prontoPaciente.setBackground(new java.awt.Color(62, 190, 76));
        prontoPaciente.setForeground(new java.awt.Color(255, 255, 255));
        prontoPaciente.setText("Pronto");
        prontoPaciente.setToolTipText("Pronto");
        prontoPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prontoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prontoPacienteActionPerformed(evt);
            }
        });

        especialidadeFuncionario.setToolTipText("Especialidade");
        especialidadeFuncionario.setName("Especialidade"); // NOI18N
        especialidadeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadeFuncionarioActionPerformed(evt);
            }
        });

        jLabel17.setText("Nome");
        jLabel17.setAlignmentY(0.0F);

        funcaoDentista.setText("Dentista");
        funcaoDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcaoDentistaActionPerformed(evt);
            }
        });

        funcaoAuxiliar.setText("Auxiliar");
        funcaoAuxiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcaoAuxiliarActionPerformed(evt);
            }
        });

        nomeFuncionario.setToolTipText("Nome");
        nomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFuncionarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome");
        jLabel5.setAlignmentY(0.0F);

        jLabel6.setText("Especialidade");
        jLabel6.setAlignmentY(0.0F);

        jLabel7.setText("Função");
        jLabel7.setAlignmentY(0.0F);

        jLabel8.setText("CRA");
        jLabel8.setAlignmentY(0.0F);

        prontoFuncionario.setBackground(new java.awt.Color(62, 190, 76));
        prontoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        prontoFuncionario.setText("Pronto");
        prontoFuncionario.setToolTipText("Pronto");
        prontoFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prontoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prontoFuncionarioActionPerformed(evt);
            }
        });

        craFuncionario.setToolTipText("CRA / Função");
        craFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                craFuncionarioActionPerformed(evt);
            }
        });

        nomePaciente.setToolTipText("Nome");
        nomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePacienteActionPerformed(evt);
            }
        });

        jLabel12.setText("CPF");
        jLabel12.setAlignmentY(0.0F);

        jLabel13.setText("Cidade");
        jLabel13.setAlignmentY(0.0F);

        cidadePaciente.setToolTipText("Cidade");
        cidadePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadePacienteActionPerformed(evt);
            }
        });

        jLabel14.setText("Telefone");
        jLabel14.setAlignmentY(0.0F);

        telefonePaciente.setToolTipText("Telefone");
        telefonePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonePacienteActionPerformed(evt);
            }
        });

        jLabel15.setText("E-mail");
        jLabel15.setAlignmentY(0.0F);

        jLabel2.setBackground(new java.awt.Color(62, 190, 76));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 190, 76));
        jLabel2.setText("Funcionário");
        jLabel2.setToolTipText("");

        emailPaciente.setToolTipText("E-mail");
        emailPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailPacienteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(62, 190, 76));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 190, 76));
        jLabel1.setText("Novo");
        jLabel1.setToolTipText("");

        jLabel16.setText("Estado");
        jLabel16.setAlignmentY(0.0F);

        jLabel3.setBackground(new java.awt.Color(62, 190, 76));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 190, 76));
        jLabel3.setText("Paciente");
        jLabel3.setToolTipText("");
        jLabel3.setMinimumSize(null);

        jLabel4.setBackground(new java.awt.Color(62, 190, 76));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(62, 190, 76));
        jLabel4.setText("Novo");
        jLabel4.setToolTipText("");

        horarioInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "07:00", "08:00", "09:00", "10:00" }));

        jLabel9.setText("Horario");
        jLabel9.setAlignmentY(0.0F);

        jLabel10.setText("Inicio");
        jLabel10.setAlignmentY(0.0F);

        horarioFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16:00", "17:00", "18:00", "19:00" }));

        jLabel18.setText("Fim");
        jLabel18.setAlignmentY(0.0F);

        try {
            cpfPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfPaciente.setToolTipText("");
        cpfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfPacienteActionPerformed(evt);
            }
        });

        voltarCadastro.setBackground(new java.awt.Color(62, 190, 76));
        voltarCadastro.setForeground(new java.awt.Color(255, 255, 255));
        voltarCadastro.setText("Voltar");
        voltarCadastro.setToolTipText("Pronto");
        voltarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadastroActionPerformed(evt);
            }
        });

        jLabel19.setText("Empresa");
        jLabel19.setAlignmentY(0.0F);

        empresaFuncionario.setToolTipText("E-mail");
        empresaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaFuncionarioActionPerformed(evt);
            }
        });

        senhaFuncionario.setToolTipText("E-mail");
        senhaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFuncionarioActionPerformed(evt);
            }
        });

        jLabel20.setText("Senha");
        jLabel20.setAlignmentY(0.0F);

        emailPaciente3.setToolTipText("E-mail");
        emailPaciente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailPaciente3ActionPerformed(evt);
            }
        });

        jLabel21.setText("Senha");
        jLabel21.setAlignmentY(0.0F);

        emailPaciente4.setToolTipText("E-mail");
        emailPaciente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailPaciente4ActionPerformed(evt);
            }
        });

        jLabel22.setText("Empresa");
        jLabel22.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nomeFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(funcaoDentista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(funcaoAuxiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(24, 24, 24)))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(horarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel9)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(horarioFim, 0, 1, Short.MAX_VALUE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(especialidadeFuncionario)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(craFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel20)
                    .addComponent(senhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empresaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nomePaciente)
                        .addComponent(jLabel12)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(emailPaciente)
                        .addComponent(telefonePaciente)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(63, 63, 63))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(estadoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(cidadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel4)
                        .addComponent(cpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21)
                    .addComponent(emailPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(emailPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(voltarCadastro)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(prontoFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prontoPaciente)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(voltarCadastro)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(funcaoDentista)
                            .addComponent(horarioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(funcaoAuxiliar)
                            .addComponent(horarioFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(especialidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(8, 8, 8)
                        .addComponent(craFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(nomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cidadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empresaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailPaciente4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailPaciente3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prontoFuncionario)
                    .addComponent(prontoPaciente))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoPacienteActionPerformed

    private void prontoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prontoPacienteActionPerformed
        // TODO add your handling code here:
        verificarCamposVaziosPaciente();
    }//GEN-LAST:event_prontoPacienteActionPerformed

    private void especialidadeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadeFuncionarioActionPerformed

    private void funcaoDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcaoDentistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcaoDentistaActionPerformed

    private void funcaoAuxiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcaoAuxiliarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcaoAuxiliarActionPerformed

    private void nomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFuncionarioActionPerformed

    private void prontoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prontoFuncionarioActionPerformed
        // TODO add your handling code here:
       inserirNovoFuncionario();
    }//GEN-LAST:event_prontoFuncionarioActionPerformed

    private void craFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_craFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_craFuncionarioActionPerformed

    private void nomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePacienteActionPerformed

    private void cidadePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadePacienteActionPerformed

    private void telefonePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonePacienteActionPerformed

    private void emailPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailPacienteActionPerformed

    private void cpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfPacienteActionPerformed

    private void voltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadastroActionPerformed
        // TODO add your handling code here:
        voltarTelaInicial();
    }//GEN-LAST:event_voltarCadastroActionPerformed

    private void empresaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaFuncionarioActionPerformed

    private void senhaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFuncionarioActionPerformed

    private void emailPaciente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailPaciente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailPaciente3ActionPerformed

    private void emailPaciente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailPaciente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailPaciente4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionar().setVisible(true);
            }
        });
    }
    
    public void voltarTelaInicial(){
        TelaInicial t = new TelaInicial();
        this.setVisible(false);
        t.setVisible(true);
    }
    
    public boolean verificarCamposVaziosFuncionario(){
        if("".equals(nomeFuncionario.getText()) || "".equals(especialidadeFuncionario.getText()) || "".equals(craFuncionario.getText())){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente");
            return false;
        }else
            return true;
    }
    
    public void verificarCamposVaziosPaciente(){
        if("".equals(nomePaciente.getText()) || "".equals(cpfPaciente.getText()) || "Selecione".equals(estadoPaciente.getSelectedItem())
                || "".equals(cidadePaciente.getText()) || "".equals(telefonePaciente.getText()) || "".equals(emailPaciente.getText())){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente");
        }
    }
    
    public void inserirNovoFuncionario(){
        FuncionarioDAO f = new FuncionarioDAO();
        Funcionario funcionario;
        EmpresaDAO empresaDAO = new EmpresaDAO();
        String funcao = " ";
        if("".equals(nomeFuncionario.getText()) || "".equals(especialidadeFuncionario.getText()) || "".equals(craFuncionario.getText())){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente");
        }
        else{
            
            if(funcaoDentista.isSelected() == true && funcaoAuxiliar.isSelected() == true){
                    JOptionPane.showMessageDialog(null,"Escolha somente uma função!");
            }
            else if(funcaoDentista.isSelected() == true && (empresaDAO.buscarEmpresa(empresaFuncionario.getText(), senhaFuncionario.getText())== true)){
                funcao = "Dentista";
                funcionario = new Funcionario(nomeFuncionario.getText(),funcao,
                    especialidadeFuncionario.getText(),craFuncionario.getText(),empresaDAO.buscarIdEmpresa(empresaFuncionario.getText()));
                boolean inserirFuncionario = f.inserirFuncionario(funcionario);
                if (inserirFuncionario == true){
                    JOptionPane.showMessageDialog(null,"Novo funcionário adicionado.");
                }
            }
            else if(funcaoAuxiliar.isSelected() == true && (empresaDAO.buscarEmpresa(empresaFuncionario.getText(), senhaFuncionario.getText())== true)){
                funcao = "Auxiliar";
                funcionario = new Funcionario(nomeFuncionario.getText(),funcao,
                    especialidadeFuncionario.getText(),craFuncionario.getText(),empresaDAO.buscarIdEmpresa(empresaFuncionario.getText()));
                boolean inserirFuncionario = f.inserirFuncionario(funcionario);
                if (inserirFuncionario == true){
                    JOptionPane.showMessageDialog(null,"Novo funcionário adicionado.");
                }
            } 
            else{
               JOptionPane.showMessageDialog(null,"Nome da empresa ou/e senha estão incorretos"); 
            }
        } 
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cidadePaciente;
    private javax.swing.JFormattedTextField cpfPaciente;
    private javax.swing.JFormattedTextField craFuncionario;
    private javax.swing.JTextField emailPaciente;
    private javax.swing.JTextField emailPaciente3;
    private javax.swing.JTextField emailPaciente4;
    private javax.swing.JTextField empresaFuncionario;
    private javax.swing.JTextField especialidadeFuncionario;
    private javax.swing.JComboBox<String> estadoPaciente;
    private javax.swing.JCheckBox funcaoAuxiliar;
    private javax.swing.JCheckBox funcaoDentista;
    private javax.swing.JComboBox<String> horarioFim;
    private javax.swing.JComboBox<String> horarioInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField nomeFuncionario;
    private javax.swing.JTextField nomePaciente;
    private javax.swing.JButton prontoFuncionario;
    private javax.swing.JButton prontoPaciente;
    private javax.swing.JTextField senhaFuncionario;
    private javax.swing.JTextField telefonePaciente;
    private javax.swing.JButton voltarCadastro;
    // End of variables declaration//GEN-END:variables
}
