/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inatel.Interface;

/**
 *
 * @author ppg10
 */
public class TelaAgenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomePacienteAtendimento = new javax.swing.JTextField();
        pesquisarAtendimento = new javax.swing.JButton();
        voltarCadastro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPesquisa = new javax.swing.JList<>();
        pesquisarAtendimento1 = new javax.swing.JButton();
        pesquisarAtendimento2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel1.setBackground(new java.awt.Color(62, 190, 76));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 190, 76));
        jLabel1.setText("Pesquisar");
        jLabel1.setToolTipText("");

        jLabel5.setText("Nome");
        jLabel5.setAlignmentY(0.0F);

        jLabel2.setBackground(new java.awt.Color(62, 190, 76));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 190, 76));
        jLabel2.setText("Atendimentos");
        jLabel2.setToolTipText("");

        nomePacienteAtendimento.setToolTipText("Nome");
        nomePacienteAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePacienteAtendimentoActionPerformed(evt);
            }
        });

        pesquisarAtendimento.setBackground(new java.awt.Color(62, 190, 76));
        pesquisarAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        pesquisarAtendimento.setText("Pesquisar");
        pesquisarAtendimento.setToolTipText("Pesquisar");
        pesquisarAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesquisarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAtendimentoActionPerformed(evt);
            }
        });

        voltarCadastro.setBackground(new java.awt.Color(62, 190, 76));
        voltarCadastro.setForeground(new java.awt.Color(255, 255, 255));
        voltarCadastro.setText("Voltar");
        voltarCadastro.setToolTipText("Pronto");
        voltarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadastroActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaPesquisa);

        pesquisarAtendimento1.setBackground(new java.awt.Color(62, 190, 76));
        pesquisarAtendimento1.setForeground(new java.awt.Color(255, 255, 255));
        pesquisarAtendimento1.setText("Excluir");
        pesquisarAtendimento1.setToolTipText("Pesquisar");
        pesquisarAtendimento1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesquisarAtendimento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAtendimento1ActionPerformed(evt);
            }
        });

        pesquisarAtendimento2.setBackground(new java.awt.Color(62, 190, 76));
        pesquisarAtendimento2.setForeground(new java.awt.Color(255, 255, 255));
        pesquisarAtendimento2.setText("Finalizar");
        pesquisarAtendimento2.setToolTipText("Pesquisar");
        pesquisarAtendimento2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesquisarAtendimento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAtendimento2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(voltarCadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pesquisarAtendimento1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisarAtendimento2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(nomePacienteAtendimento, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pesquisarAtendimento))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(voltarCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePacienteAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarAtendimento))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarAtendimento1)
                    .addComponent(pesquisarAtendimento2))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomePacienteAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePacienteAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePacienteAtendimentoActionPerformed

    private void pesquisarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAtendimentoActionPerformed
        // TODO add your handling code here:
        pesquisarAtendimentos();
    }//GEN-LAST:event_pesquisarAtendimentoActionPerformed

    private void voltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadastroActionPerformed
        // TODO add your handling code here:
        voltarTelaInicial();
    }//GEN-LAST:event_voltarCadastroActionPerformed

    private void pesquisarAtendimento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAtendimento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarAtendimento1ActionPerformed

    private void pesquisarAtendimento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAtendimento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarAtendimento2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }
    
    public void voltarTelaInicial(){
        TelaInicial t = new TelaInicial();
        this.setVisible(false);
        t.setVisible(true);
    }
    
    public void pesquisarAtendimentos(){  
        String[] atendimentos = new String[5];
        for(int i=0;i<5;i++){
            atendimentos[i] = "Pedro Guimarães | 19:00 | 20/04/2022 | Francilene Silva" ;
        }
        listaPesquisa.setListData(atendimentos);
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPesquisa;
    private javax.swing.JTextField nomePacienteAtendimento;
    private javax.swing.JButton pesquisarAtendimento;
    private javax.swing.JButton pesquisarAtendimento1;
    private javax.swing.JButton pesquisarAtendimento2;
    private javax.swing.JButton voltarCadastro;
    // End of variables declaration//GEN-END:variables
}
