/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inatel.Interface;

import com.inatel.Integracao.DAO.EmpresaDAO;
import com.inatel.Integracao.Model.Empresa;
import javax.swing.JOptionPane;

/**
 *
 * @author ppg10
 */
public class TelaEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmpresa
     */
    public TelaEmpresa() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeEmpresaNova = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        prontoFuncionario = new javax.swing.JButton();
        prontoEmpresaNova = new javax.swing.JButton();
        nomeEmpresaExistente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        senhaEmpresaNova = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        senhaEmpresaExistente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));

        jLabel2.setBackground(new java.awt.Color(62, 190, 76));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 190, 76));
        jLabel2.setText("Empresa");
        jLabel2.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(62, 190, 76));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 190, 76));
        jLabel1.setText("Nova");
        jLabel1.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(62, 190, 76));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 190, 76));
        jLabel3.setText("Existente");
        jLabel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(62, 190, 76));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(62, 190, 76));
        jLabel4.setText("Empresa");
        jLabel4.setToolTipText("");

        nomeEmpresaNova.setToolTipText("Nome");
        nomeEmpresaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpresaNovaActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome");
        jLabel5.setAlignmentY(0.0F);

        prontoFuncionario.setBackground(new java.awt.Color(62, 190, 76));
        prontoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        prontoFuncionario.setText("Pronto");
        prontoFuncionario.setToolTipText("Pronto");
        prontoFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prontoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prontoFuncionarioActionPerformed(evt);
            }
        });

        prontoEmpresaNova.setBackground(new java.awt.Color(62, 190, 76));
        prontoEmpresaNova.setForeground(new java.awt.Color(255, 255, 255));
        prontoEmpresaNova.setText("Pronto");
        prontoEmpresaNova.setToolTipText("Pronto");
        prontoEmpresaNova.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prontoEmpresaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prontoEmpresaNovaActionPerformed(evt);
            }
        });

        nomeEmpresaExistente.setToolTipText("Nome");
        nomeEmpresaExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpresaExistenteActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome");
        jLabel6.setAlignmentY(0.0F);

        jLabel7.setText("Senha");
        jLabel7.setAlignmentY(0.0F);

        senhaEmpresaNova.setToolTipText("Nome");
        senhaEmpresaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaEmpresaNovaActionPerformed(evt);
            }
        });

        jLabel8.setText("Senha");
        jLabel8.setAlignmentY(0.0F);

        senhaEmpresaExistente.setToolTipText("Nome");
        senhaEmpresaExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaEmpresaExistenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeEmpresaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(prontoEmpresaNova)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaEmpresaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(senhaEmpresaExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(nomeEmpresaExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addComponent(prontoFuncionario)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeEmpresaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaEmpresaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prontoEmpresaNova)
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeEmpresaExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaEmpresaExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prontoFuncionario)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeEmpresaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpresaNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpresaNovaActionPerformed

    private void prontoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prontoFuncionarioActionPerformed
        // TODO add your handling code here:
        verificarEmpresa();
    }//GEN-LAST:event_prontoFuncionarioActionPerformed

    private void prontoEmpresaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prontoEmpresaNovaActionPerformed
        // TODO add your handling code here:
        adicionarEmpresa();
    }//GEN-LAST:event_prontoEmpresaNovaActionPerformed

    private void nomeEmpresaExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpresaExistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpresaExistenteActionPerformed

    private void senhaEmpresaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaEmpresaNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaEmpresaNovaActionPerformed

    private void senhaEmpresaExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaEmpresaExistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaEmpresaExistenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmpresa().setVisible(true);
            }
        });
    }
    
    public void adicionarEmpresa(){
        EmpresaDAO e = new EmpresaDAO();
        Empresa empresa;
        
        if("".equals(nomeEmpresaNova.getText()) || "".equals(senhaEmpresaNova.getText())){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente");
        }else{
            empresa = new Empresa(nomeEmpresaNova.getText(),senhaEmpresaNova.getText());
            boolean inserirEmpresa = e.inserirEmpresa(empresa);
            if (inserirEmpresa == true){
                JOptionPane.showMessageDialog(null,"Nova empresa adicionado.");
            }
            TelaInicial t = new TelaInicial();
            this.setVisible(false);
            t.setVisible(true);
        }
    }
    
    public void verificarEmpresa(){
        EmpresaDAO empresaDAO = new EmpresaDAO();
        if("".equals(nomeEmpresaExistente.getText()) || "".equals(senhaEmpresaExistente.getText())){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente");
        }else if(empresaDAO.buscarEmpresa(nomeEmpresaExistente.getText(), senhaEmpresaExistente.getText())== true){
            TelaInicial t = new TelaInicial();
            this.setVisible(false);
            t.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Nome da empresa ou senha estão incorretos");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomeEmpresaExistente;
    private javax.swing.JTextField nomeEmpresaNova;
    private javax.swing.JButton prontoEmpresaNova;
    private javax.swing.JButton prontoFuncionario;
    private javax.swing.JTextField senhaEmpresaExistente;
    private javax.swing.JTextField senhaEmpresaNova;
    // End of variables declaration//GEN-END:variables
}
