/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inatel.Interface;

import com.inatel.Integracao.DAO.AtendimentoDAO;
import com.inatel.Integracao.Model.Atendimento;
import java.util.ArrayList;

/**
 *
 * @author ppg10
 */
public class TelaAgenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomePacienteAtendimento = new javax.swing.JTextField();
        pesquisaAgenda = new javax.swing.JButton();
        voltarCadastro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPesquisa = new javax.swing.JList<>();
        excluirAtendimento = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPesquisa1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        finalizarAtendimento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel1.setBackground(new java.awt.Color(62, 190, 76));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 190, 76));
        jLabel1.setText("Pesquisar");
        jLabel1.setToolTipText("");

        jLabel5.setText("Nome");
        jLabel5.setAlignmentY(0.0F);

        jLabel2.setBackground(new java.awt.Color(62, 190, 76));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 190, 76));
        jLabel2.setText("Atendimentos");
        jLabel2.setToolTipText("");

        nomePacienteAtendimento.setToolTipText("Nome");
        nomePacienteAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePacienteAtendimentoActionPerformed(evt);
            }
        });

        pesquisaAgenda.setBackground(new java.awt.Color(62, 190, 76));
        pesquisaAgenda.setForeground(new java.awt.Color(255, 255, 255));
        pesquisaAgenda.setText("Pesquisar");
        pesquisaAgenda.setToolTipText("Pesquisar");
        pesquisaAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesquisaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaAgendaActionPerformed(evt);
            }
        });

        voltarCadastro.setBackground(new java.awt.Color(62, 190, 76));
        voltarCadastro.setForeground(new java.awt.Color(255, 255, 255));
        voltarCadastro.setText("Voltar");
        voltarCadastro.setToolTipText("Pronto");
        voltarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadastroActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaPesquisa);

        excluirAtendimento.setBackground(new java.awt.Color(62, 190, 76));
        excluirAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        excluirAtendimento.setText("Excluir");
        excluirAtendimento.setToolTipText("Pesquisar");
        excluirAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excluirAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAtendimentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Abertos");
        jLabel6.setAlignmentY(0.0F);

        jScrollPane2.setViewportView(listaPesquisa1);

        jLabel7.setText("Finalizados");
        jLabel7.setAlignmentY(0.0F);

        finalizarAtendimento.setBackground(new java.awt.Color(62, 190, 76));
        finalizarAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        finalizarAtendimento.setText("Finalizar");
        finalizarAtendimento.setToolTipText("Pesquisar");
        finalizarAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finalizarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarAtendimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(voltarCadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(finalizarAtendimento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(excluirAtendimento))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(nomePacienteAtendimento, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(pesquisaAgenda))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(voltarCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePacienteAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisaAgenda))
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirAtendimento)
                    .addComponent(finalizarAtendimento))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomePacienteAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePacienteAtendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePacienteAtendimentoActionPerformed

    private void pesquisaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaAgendaActionPerformed
        // TODO add your handling code here:
        pesquisarAtendimentos();
    }//GEN-LAST:event_pesquisaAgendaActionPerformed

    private void voltarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadastroActionPerformed
        // TODO add your handling code here:
        voltarTelaInicial();
    }//GEN-LAST:event_voltarCadastroActionPerformed

    private void excluirAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAtendimentoActionPerformed
        // TODO add your handling code here:
        deletarAtendimento();
    }//GEN-LAST:event_excluirAtendimentoActionPerformed

    private void finalizarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarAtendimentoActionPerformed
        // TODO add your handling code here:
        finalizarAtendimento();
    }//GEN-LAST:event_finalizarAtendimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }
    
    public void voltarTelaInicial(){
        TelaInicial t = new TelaInicial();
        this.setVisible(false);
        t.setVisible(true);
    }
    
    public void pesquisarAtendimentos(){  
        AtendimentoDAO a = new AtendimentoDAO();
        ArrayList<Atendimento> listaAtendimentos;
        listaAtendimentos = a.pesquisarAtendimento(nomePacienteAtendimento.getText());
        String atendimentosAbertos[] = new String[listaAtendimentos.size()];
        String atendimentosFechados[] = new String[listaAtendimentos.size()];
        for(int i=0;i<listaAtendimentos.size();i++){
            if("aberto".equals(listaAtendimentos.get(i).getSituacao())){
                atendimentosAbertos[i] ="Id: " +
                    listaAtendimentos.get(i).getId() + " | Nome: " + nomePacienteAtendimento.getText() + " | Data: " + listaAtendimentos.get(i).getData() + " | Hora: " + 
                    listaAtendimentos.get(i).getHora() + " | Procedimento: " + listaAtendimentos.get(i).getProcedimento();
            }else if("finalizado".equals(listaAtendimentos.get(i).getSituacao())){
                atendimentosFechados[i] ="Id: " +
                    listaAtendimentos.get(i).getId() + " | Nome: " + nomePacienteAtendimento.getText() + " | Data: " + listaAtendimentos.get(i).getData() + " | Hora: " + 
                    listaAtendimentos.get(i).getHora() + " | Procedimento: " + listaAtendimentos.get(i).getProcedimento();
            }
            
        }
        listaPesquisa.setListData(atendimentosAbertos);
        listaPesquisa1.setListData(atendimentosFechados);
    };
    
    public void deletarAtendimento(){
        AtendimentoDAO a = new AtendimentoDAO();
        String s = (String) listaPesquisa.getSelectedValue();
        int id =  Integer. valueOf(s.substring(4, 5));
        a.deletarAtendimento(id);
        pesquisarAtendimentos();
    }
    
    public void finalizarAtendimento(){
        AtendimentoDAO a = new AtendimentoDAO();
        String s = (String) listaPesquisa.getSelectedValue();
        int id =  Integer. valueOf(s.substring(4, 5));
        a.updateAtendimento(id);
        pesquisarAtendimentos();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton excluirAtendimento;
    private javax.swing.JButton finalizarAtendimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPesquisa;
    private javax.swing.JList<String> listaPesquisa1;
    private javax.swing.JTextField nomePacienteAtendimento;
    private javax.swing.JButton pesquisaAgenda;
    private javax.swing.JButton voltarCadastro;
    // End of variables declaration//GEN-END:variables
}
